# Generated by Django 4.1.3 on 2022-11-16 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('craetion_datetime', models.DateTimeField(auto_now=True)),
                ('correct', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=320)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('craetion_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tag')),
            ],
            options={
                'db_table': 'question_tag',
            },
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('l', 'Like'), ('d', 'Dislike')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.profile')),
            ],
            options={
                'db_table': 'question_like',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(through='app.QuestionTag', to='app.tag'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.profile'),
        ),
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('l', 'Like'), ('d', 'Dislike')], max_length=1)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.profile')),
            ],
            options={
                'db_table': 'answer_like',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.profile'),
        ),
    ]
